# Generated by Django 4.2.11 on 2024-05-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('developer', models.CharField(max_length=70)),
                ('appointment', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=70)),
                ('measurement', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField(default=0.0)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
    ]
