# Generated by Django 4.2.11 on 2024-05-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='category',
        ),
    ]
