# Generated by Django 4.2.11 on 2024-05-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='drug',
            name='about_product',
            field=models.TextField(blank=True),
        ),
    ]
