# Generated by Django 4.2.11 on 2024-05-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_drug_is_booked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drug',
        ),
    ]
