# Generated by Django 4.2.11 on 2024-05-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='main/img/149071.png', upload_to='main/'),
        ),
    ]
